---
output: github_document
---


# Intermediate R

### Course Description

Welcome to Intermediate R\! This short course builds onto the [Intro to R](https://github.com/uc-r/Intro-R) course and provides a hands-on
approach to using the R programming language for data science
applications. In this course you will learn about various workflow approaches,
scoped variable transformation, control flow, iteration with loops, iteration 
with functional programming, and how to write _good_ functions. The
following is an outline of the material covered in this training:

**Day 1**

| Topic                                                                          |     Time      |
| :----------------------------------------------------------------------------- | :-----------: |
| Breakfast / Social time                                                        |  8:00 - 9:00  |
| [Introductions](https://uc-r.github.io/Intermediate-R/day-1a-intro.html)       |  9:00 - 9:30  |
| [Scoped variable transformations](https://uc-r.github.io/Intermediate-R/day-1b-scoped-dplyr.html)  |  9:30 - 10:45 |
| Break                                                                          | 10:45 - 11:00 |
| [Control statements](https://uc-r.github.io/Intermediate-R/day-1c-control-flow.html) | 11:00 - 12:00 |
| Lunch                                                                          | 12:00 - 1:00  |
| [Workflow](https://uc-r.github.io/Intermediate-R/day-1d-workflow.html)         |  1:00 - 2:30  |
| Break                                                                          |  2:30 - 2:45  |
| [Case study](https://uc-r.github.io/Intermediate-R/day-1e-case-study.html)   |  2:45 - 4:00  |
| Q\&A                                                                           |  4:00 - 4:30  |

**Day 2**

| Topic                                                                         |     Time      |
| :---------------------------------------------------------------------------- | :-----------: |
| Breakfast / Social time                                                       |  8:00 - 9:00  |
| [Review](https://uc-r.github.io/Intermediate-R/day-2a-intro.html)             |  9:00 - 9:30  |
| [Iteration with loops](https://uc-r.github.io/Intermediate-R/day-2b-loops.html) |  9:30 - 10:30 |
| Break                                                                         | 10:30 - 10:45 |
| [Iteration with functional programming](https://uc-r.github.io/Intermediate-R/day-2c-fp.html) | 10:45 - 12:00 |
| Lunch                                                                         | 12:00 - 1:00  |
| [Writing functions](https://uc-r.github.io/Intermediate-R/day-2d-functions.html) |  1:00 - 2:30  |
| Break                                                                         |  2:30 - 2:45  |
| [Case study](https://uc-r.github.io/Intermediate-R/day-2e-case-study.html)    |  2:45 - 4:00  |
| Q\&A                                                                          |  4:00 - 4:30  |

### Course Preparation

To prepare for this course please complete the following ***prior*** to
the day of class:

1.  Download the class material at [TBD]().
    This will provide you with the data and R scripts to follow along
    during class. I have also included handy cheat sheets that you can
    reference throughout different sections.

2.  All slides are available via the hyperlinks in the schedule above so
    that you can follow along.

3.  Please have the following versions of R and RStudio installed. If
    you have an earlier version of R that is at least version 3.4.5 or
    later you should be ok but its best to be as current as possible.
    
      - R: 3.5.1 \[[download latest
        version](https://cran.r-project.org/)\]
      - RStudio: 1.1.463 \[[download latest
        version](https://www.rstudio.com/products/rstudio/download/#download)\]
        
4. This course makes some assumptions about your prior knowledge. To ensure your
   success, be sure that you have reviewed and are comfortable with the material
   covered in the [Intro to R](https://github.com/uc-r/Intro-R) course. 
   
If you have any specific questions prior to the class you can reach out to me 
(Brad Boehmke) directly at [bradleyboehmke@gmail.com](mailto:bradleyboehmke@gmail.com).